export const GET_BRANCHES = "GET_BRANCHES"
export const GET_BRANCHES_REQUESTED = "GET_BRANCHES_REQUESTED"
export const SET_CURRENT_BRANCH = "SET_CURRENT_BRANCH"
export const SET_CURRENT_BRANCH_REQUESTED = "SET_CURRENT_BRANCH_REQUESTED"