export const GET_COMMITS = "GET_COMMITS"
export const GET_COMMITS_REQUESTED = "GET_COMMITS_REQUESTED"
export const SET_CURRENT_PAGE="SET_CURRENT_PAGE"
export const SET_CURRENT_PAGE_REQUESTED="SET_CURRENT_PAGE_REQUESTED"